version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_PASSWORD=password
  backend:
    build:
      context: .
      dockerfile: backend_dockerfile
    command: bash -c "
        wait-for-it db:5432 -- python3 manage.py migrate
        && python manage.py collectstatic
        && gunicorn stocks_products.wsgi:crud -b 0.0.0.0:8000"
    volumes:
      - ./crud:/crud
    working_dir: /crud/stocks_products
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: web_dockerfile
    depends_on:
      - backend
    command: bash -c "
        wait-for-it backend:8000 -- nginx -g 'daemon off;'"
    ports:
      - "80:80"
